import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// PassportIDPhotoMaker — generated by AppFactoryKit appgen from niche "id-photo-maker".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum PassportIDPhotoMakerFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "PassportIDPhotoMaker",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "doc.viewfinder",
                          title: "PassportIDPhotoMaker",
                          message: "Compliant passport/visa/ID photos from a selfie."),
                    .init(systemImage: "doc.text.magnifyingglass",
                          title: "Go Pro",
                          message: "All country sizes, background removal, print sheet.")
                ],
                presentsPaywallOnFinish: true,
                accent: .blue
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock PassportIDPhotoMaker Pro",
                subheadline: "All country sizes, background removal, print sheet.",
                benefits: [
                    .init(systemImage: "infinity", title: "All country sizes"),
                    .init(systemImage: "bolt.fill", title: "Background removal"),
                    .init(systemImage: "nosign", title: "Print sheet")
                ],
                productIDs: ["id-photo-maker_yearly", "id-photo-maker_weekly"],
                highlightedProductID: "id-photo-maker_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .blue, heroSystemImage: "doc.viewfinder")
            )
        )
        return AppFactory(config)
    }
}

@main
struct PassportIDPhotoMakerApp: App {
    @StateObject private var factory = PassportIDPhotoMakerFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.blue)
        }
    }
}
